apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-deployment
spec:
  selector:
    matchLabels:
      app: ruby
  replicas: 2
  template:
    metadata:
      labels:
        app: ruby
    spec:
      containers:
      - name: ruby
        image: abdullahxy/ruby-sqlite-app:v1
        ports:
        - containerPort: 3000
