# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1 # v1.92
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      # Add or replace database setup steps here
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev
          gem update --system
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake
          
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1 # v1.92
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      # Add or replace any other lints here
      - name: Lint Ruby files
        run: bin/rubocop --parallel
