# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
  
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
          
      - name: Build and run tests
        env:
          RAILS_ENV: test
        run: |
          sudo apt-get install libsqlite3-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails test
